---
shared:
  :dsi_users:
    - id
    - email
    - first_name
    - last_name
    - uid
    - created_at
    - updated_at
  :feature_flags_features:
    - id
    - name
    - active
    - created_at
    - updated_at
