---
shared:
  :childrens_barred_list_entries:
    - id
    - trn
    - first_names
    - last_name
    - searchable_last_name
    - date_of_birth
    - national_insurance_number
    - confirmed
    - confirmed_at
    - upload_file_hash
    - created_at
    - updated_at
  :roles:
    - id
    - code
    - enabled
    - internal
    - created_at
    - updated_at
  :sessions:
    - id
    - session_id
    - data
    - created_at
    - updated_at
