---
shared:
  :active_storage_variant_records:
    - id
    - blob_id
    - variation_digest
  :active_storage_blobs:
    - id
    - key
    - filename
    - content_type
    - metadata
    - service_name
    - byte_size
    - checksum
    - created_at
  :active_storage_attachments:
    - id
    - name
    - record_type
    - record_id
    - blob_id
    - created_at
  :dsi_users:
    - id
    - email
    - first_name
    - last_name
    - uid
    - created_at
    - updated_at
  :feature_flags_features:
    - id
    - name
    - active
    - created_at
    - updated_at
