---
shared:
  :dsi_users:
    - id
    - email
    - first_name
    - last_name
    - uid
    - created_at
    - updated_at
    - terms_and_conditions_version_accepted
    - terms_and_conditions_accepted_at
  :dsi_user_sessions:
    - id
    - dsi_user_id
    - role_id
    - role_code
    - organisation_id
    - organisation_name
    - created_at
    - updated_at
  :feature_flags_features:
    - id
    - name
    - active
    - created_at
    - updated_at
  :feedbacks:
    - id
    - satisfaction_rating
    - improvement_suggestion
    - contact_permission_given
    - email
    - created_at
    - updated_at
  :search_logs:
    - id
    - dsi_user_id
    - last_name
    - date_of_birth
    - result_returned
    - created_at
    - updated_at
