name: Delete Review App

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number of review app to delete
        required: false
        type: string

jobs:
  delete-review-app:
    name: Delete Review App ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
    concurrency: deploy_review_${{ github.event.pull_request.number || github.event.inputs.pr_number }}
    runs-on: ubuntu-latest
    if: >
      (github.event.action == 'closed' && github.event.label.name == 'deploy') ||
      (github.event.action == 'unlabeled' && github.event.label.name == 'deploy') || (github.event_name ==
      'workflow_dispatch')

    environment: review
    permissions:
      pull-requests: write
      id-token: write

    steps:
      - name: Set environment variables
        id: app_name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "APP_NAME=pr-${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
          else
            echo "APP_NAME=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          fi

      - uses: DFE-Digital/github-actions/delete-review-app@master
        with:
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          gcp-wip: projects/708780292301/locations/global/workloadIdentityPools/check-childrens-barred-list/providers/check-childrens-barred-list
          gcp-project-id: teaching-qualifications
          terraform-base: terraform/aks
          pr-number: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          resource-group-name: s189t01-ccbl-rv-rg
          storage-account-name: s189t01ccbltfstatervsa
          container-name: terraform-state
          tf-state-file: pr-${{ github.event.pull_request.number || github.event.inputs.pr_number }}.tfstate
